Update date.py
First, I found an issue in the to_joda_datetime() function where passing it a python datetime.datetime object would throw an error: 
IllegalArgumentException: java.lang.IllegalArgumentException: The datetime zone id 'GMT-05:00' is not recognised
I believe this is because java ZoneOffset.getId is expecting just "-05:00" without the 'GMT', and is "incompatible" with the python zone ID.  I modified the code slightly and replace "GMT" with "", and it clears up the problem for me. (line 305-308)

Also, I added a millis() function to get millis past unix epoch, a joda_now() function to simplify getting the current joda datetime string or object, an elapsed function to get various formats of elapsed time between two datetime objects or joda datetime strings, and a str_to_python_datetime() function to allow passing a joda datetime string into all of the other conversion functions within this library.

Note: I did this because I have all of these functions in a separate personal library and I wanted to combine them, and I also wanted to learn about github and the fork/pull process.  Please let me know if I'm breaking some kind of etiquette rules here! Thanks.